name: CC Autograde

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn clean test
      env:
        AID: "5632499082330112"
        CID: "eb0e8e5e-0e11-4f9b-89cd-3fe4ee624c0e"
                                    
